services:
  nest-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mysql-container
      - redis-container
  mysql-container:
    image: mariadb:10.6
    restart: always
    ports:
      - '3360:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
    volumes:
      - ./mysql:/var/lib/mysql
  redis-container:
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./redis:/data
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "mysql-container"
      PMA_USER: "root"
      PMA_PASSWORD: "root"
